### ISSUE TITLE
Git Error: authentication required but no callback set; class=Ssh (23)

### ISSUE THREAD

**Issue by AllenDang** [MoAlyousef/fl2rust-template#1]
I got following error, any idea?

```sh
❯ cargo generate --git https://github.com/fltk-rs/fl2rust-template
🤷   Project Name : test
🔧   Creating project called `test`...
Error: ⛔   Git Error: authentication required but no callback set; class=Ssh (23)
```

**Comment by MoAlyousef** [comment]
I'm not sure. I just tried now on a github actions worker and it works. You can maybe try a different project name since I think 'test' is not allowed. Or maybe it's an ssl/libgit authentication issue or an issue with cargo-generate on your system.
